image: fpco/stack-build-small:lts-18.12

stages:
  - build
  - lint
  - test
  - haddock

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

build:
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .stack-work/
      - .stack-root/
  script:
    - stack --no-terminal build

lint:
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .stack-work/
      - .stack-root/
  script:
    - curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s . --report
  artifacts:
    paths:
      - report.html


test:
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .stack-work/
      - .stack-root/
  script:
    - stack --no-terminal test

haddock:
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .stack-work/
      - .stack-root/
  script:
    - stack --no-terminal haddock
  artifacts:
    paths:
      - index.html
      - substep.txt
