name:                substep
version:             0.1.0.0
license:             GPL-3
author:              "haskell-substitution-stepper"
maintainer:          "haskell-substitution-stepper"
copyright:           "2021 haskell-substitution-stepper"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the manual on <http://haskell-substitution-stepper.pages.gitlab.ost.ch/product-docu/index.html>

dependencies:
- base >= 4.7 && < 5
- hlint
- apply-refact
- mtl
- containers
- exceptions
- bytestring
- text
- filepath
- directory
- ghc-lib
- ghc-lib-parser
- ghc-paths
- optparse-applicative
- optparse-generic
- hspec
- deepseq

library:
  source-dirs: src

executables:
  substep:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - substep

tests:
  substep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - substep
    - hspec
    - deepseq
